server:
  port: 8081


#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/



spring:
  application:
    name: users-service
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: aman1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    import: configserver:http://localhost:8085
#  profiles:
#    active: dev

  jpa:
    hibernate:
        ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect



management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

  retry:
    instances:
      ratingHotelService:
        maxAttempts: 3
        waitDuration: 3s

  ratelimiter:
    instances:
      userRateLimiter:
        limitRefreshPeriod: 4s
        limitForPeriod: 2
        timeoutDuration: 2s

      userRateLimiterAllData:
        limitRefreshPeriod: 4s
        limitForPeriod: 2
        timeoutDuration: 3s

