#
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false

  server:
    wait-time-in-ms-when-sync-empty: 0
server:
  port: 8761


#
#


#eureka:
#  instance:
#    prefer-ip-address: true
#    hostname: localhost
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#
#
#server:
#  port: 8081
#
#  spring:
#    datasource:
#      url: jdbc:mysql://localhost:3306/microservicesRegistry
#      username: root
#      password: aman1234
#      driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#
#
#  application:
#    name: USER-SERVICE